# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "github-pages", group: :jekyll_plugins

gem "jekyll", "~> 3.9.3"

gem "jekyll-remote-theme", "~> 0.4.3"

gem "jekyll-seo-tag", "~> 2.8"

gem "webrick", "~> 1.8"
